ai-entities:
  product:
    indexing:
      enabled: true
      max-characters: 8000

  policy:
    indexing:
      enabled: true
      max-characters: 8000

  review:
    indexing:
      enabled: true
      max-characters: 8000
