CREATE TABLE IF NOT EXISTS ai_behavior_insights (
  id UUID PRIMARY KEY,
  user_id VARCHAR(255) UNIQUE NOT NULL,
  segment VARCHAR(100),
  patterns CLOB,
  recommendations CLOB,
  insights CLOB,
  sentiment_score DOUBLE,
  sentiment_label VARCHAR(50),
  churn_risk DOUBLE,
  churn_reason TEXT,
  previous_sentiment_score DOUBLE,
  previous_churn_risk DOUBLE,
  trend VARCHAR(50),
  analyzed_at TIMESTAMP,
  confidence DOUBLE,
  ai_model_used VARCHAR(100),
  model_prompt_version VARCHAR(20),
  processing_time_ms BIGINT,
  created_at TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_behavior_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  external_event_id VARCHAR(160),
  payload_fingerprint VARCHAR(64),
  event_type VARCHAR(120) NOT NULL,
  event_timestamp TIMESTAMP NOT NULL,
  event_data CLOB,
  source VARCHAR(120)
);

CREATE INDEX IF NOT EXISTS idx_app_behavior_event_user_ts ON app_behavior_event(user_id, event_timestamp);
CREATE UNIQUE INDEX IF NOT EXISTS ux_app_behavior_event_external ON app_behavior_event(user_id, external_event_id);

CREATE TABLE IF NOT EXISTS app_behavior_analysis_job (
  id UUID PRIMARY KEY,
  invocation_id VARCHAR(120) UNIQUE NOT NULL,
  session_id VARCHAR(180) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  idempotency_key VARCHAR(200) NOT NULL,
  previous_insight_json CLOB,
  considered_events_json CLOB NOT NULL,
  considered_event_count INTEGER NOT NULL,
  submitted_at TIMESTAMP NOT NULL,
  applied_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_behavior_analysis_job_session ON app_behavior_analysis_job(session_id, submitted_at);
CREATE INDEX IF NOT EXISTS idx_behavior_analysis_job_user ON app_behavior_analysis_job(user_id, submitted_at);

CREATE TABLE IF NOT EXISTS ai_specialist_execution (
  invocation_id VARCHAR(120) PRIMARY KEY,
  specialist_name VARCHAR(120) NOT NULL,
  specialist_version VARCHAR(80) NOT NULL,
  specialist_content_hash VARCHAR(64) NOT NULL,
  access_fingerprint VARCHAR(64) NOT NULL,
  idempotency_fingerprint VARCHAR(64) UNIQUE,
  request_fingerprint VARCHAR(64) NOT NULL,
  protected_request CLOB NOT NULL,
  protected_result CLOB,
  status VARCHAR(40) NOT NULL,
  failure_reason VARCHAR(160),
  deadline TIMESTAMP NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  completed_at TIMESTAMP,
  expires_at TIMESTAMP NOT NULL,
  lease_owner VARCHAR(160),
  lease_until TIMESTAMP,
  attempt_count INTEGER NOT NULL,
  version BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ai_execution_recovery ON ai_specialist_execution(status, lease_until, updated_at);
CREATE INDEX IF NOT EXISTS idx_ai_execution_expiry ON ai_specialist_execution(completed_at);
CREATE INDEX IF NOT EXISTS idx_ai_execution_access ON ai_specialist_execution(access_fingerprint);

CREATE TABLE IF NOT EXISTS intent_history (
  id VARCHAR(255) PRIMARY KEY,
  user_id VARCHAR(255) NOT NULL,
  session_id VARCHAR(255),
  query_redacted CLOB,
  query_encrypted CLOB,
  intents_json CLOB,
  result_json CLOB,
  metadata_json CLOB,
  execution_status VARCHAR(50),
  success BOOLEAN,
  has_sensitive_data BOOLEAN,
  sensitive_data_types VARCHAR(512),
  intent_count INTEGER,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_intent_history_user ON intent_history(user_id);
CREATE INDEX IF NOT EXISTS idx_intent_history_created ON intent_history(created_at);
CREATE INDEX IF NOT EXISTS idx_intent_history_expires ON intent_history(expires_at);
