ai-entities:
  sync-product:
    indexing:
      enabled: true
      max-characters: 8000

  sync-policy:
    indexing:
      enabled: true
      max-characters: 8000

  sync-guide:
    indexing:
      enabled: true
      max-characters: 8000
